apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokedex-flask
  labels:
    app: pokedex-flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pokedex-flask
  template:
    metadata:
      labels:
        app: pokedex-flask
    spec:
      containers:
      - name: pokedex
        image: abelucci/pokedex-flask:1
        ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name:  service-pokedex
spec:
  selector:
    app: pokedex-flask
  type: NodePort
  ports:
  - protocol: TCP
    port:  5000
    targetPort:  5000