apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokedex-flask-deploy
  labels:
    app: pokedex-flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pokedex-flask
  template:
    metadata:
      labels:
        app: pokedex-flask
  spec:
      containers:
      - name: pokedex
        image: abelucci/pokedex-flask-prometheus:1
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
    name: pokedex-service
spec:
    type: NodePort
    selector:
        app: pokedex-flask
    ports:
      - protocol: TCP 
        port: 5000
        targetPort: 5000