apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokedex-flask-deploy
  labels:
    app: pokedex-flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pokedex-flask
  template:
    metadata:
      labels:
        app: pokedex-flask
    spec:
      containers:
      - name: pokedex
        image: abelucci/pokedex-flask-prometheus:1
        ports:
        - containerPort: 5000
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /metrics
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 3