apiVersion: v1
kind: Service
metadata:
    name: pokedex-prometheus-service
spec:
    type: NodePort
    selector:
        app: pokedex-flask
    ports:
      - protocol: TCP 
        port: 5000
        targetPort: 5000
        name: http
      - protocol: TCP 
        port: 8000
        targetPort: 8000
        name: metrics