apiVersion: apps/v1
kind: Deployment
metadata:
  name: agenda-deployment
  labels:
    app: agenda-app ## nombre de la app para matchear con otros specs
    
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: agenda-app
  template:
    metadata:
      labels:
        app: agenda-app
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google_samples/gb-frontend:v3
        ports:
        - containerPort: 80
